$Env:PROGRAMATIC_EXPOSE_PORT = 8002
$Env:PROGRAMATIC_SERVICE_NAME = "catalog"
$Env:PROGRAMATIC__SERVICE_INSTANCE_ID = "catalog-instance-1"
$Env:PROGRAMATIC_HOST="localhost"
$Env:PROGRAMATIC_OTLP_ENDPOINT = "http://localhost:4317"
$Env:OTEL_PYTHON_LOG_CORRELATION = "true"
$Env:OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED = "true"
python catalog-server.py